blog/urls.py
from django.urls import path
from . import views

app_name= 'blog'

urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('category/<int:category_id>/', views.category, name="category"),      
]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.contact, name='contact'),
    
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('store/', views.store, name='store'),
    
]

pages/urls.py
from django.urls import path
from .import views

urlpatterns = [
    
    path('<int:page_id>/', views.page, name="page"),      
]

services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.services, name= 'services'),
        
]

webempresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns =[
    
    #Paths del core
    path('', include('core.urls')),
    
    #Paths del services
    path('services/', include('services.urls')),
    
    #Paths del blog
    path('blog/', include('blog.urls')),
    
    #Paths del pages
    path('page/', include('pages.urls')),
    
    #Paths de contact
    path('contact/', include('contact.urls')),
    
    #Paths del admin
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    from django.conf.urls.static  import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

        

blog/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models  import User

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=100, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add= True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now= True, verbose_name= "Fecha de edición")
    
    class Meta:
        verbose_name = "categoría"
        verbose_name_plural = "categorias"
        ordering = ['-created']
    
    def __str__(self):
        return self.name
    
    
class Post(models.Model):
    title= models.CharField(max_length=200, verbose_name="Título")
    content=models.TextField(verbose_name="Contenido")
    published=models.DateField(verbose_name="Fecha de publicación", default=now)
    image= models.ImageField(verbose_name="Imagen", upload_to="blog", null=True, blank=True)
    author= models.ForeignKey(User, verbose_name="Autor", on_delete=models.CASCADE)
    categories= models.ManyToManyField(Category, verbose_name="Categorías", related_name="get_posts")
    created = models.DateTimeField(auto_now_add= True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now= True, verbose_name= "Fecha de edición")
    
    class Meta:
        verbose_name = "entrada"
        verbose_name_plural = "entradas"
        ordering = ['-created']
    
    def __str__(self):
        return self.title
    

contact/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class Page(models.Model):
    title=models.CharField(verbose_name="Título", max_length=200)
    content=RichTextField(verbose_name="Contenido")
    order=models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add= True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now= True, verbose_name= "Fecha de edición")
    
    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering =['order', 'title']
    
    def __str__(self):
        return self.title 

services/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    title = models.CharField(max_length= 200, verbose_name = "Título")
    subtitle = models.CharField(max_length= 200, verbose_name = "Subtítulo")
    content = models.TextField(verbose_name = "Contenido")
    image = models.ImageField(verbose_name= "imagen", upload_to= "services")
    created = models.DateTimeField(auto_now_add= True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now= True, verbose_name= "Fecha de edición")
    
    class Meta:
        verbose_name = "servicio"
        verbose_name_plural = "servicios"
        ordering = ['-created']
    
    def __str__(self):
        return self.title

social/models.py
from django.db import models

# Create your models here.

class Link(models.Model):
    key=models.SlugField(verbose_name="Nombre clave", max_length=100, unique=True)
    name=models.CharField(verbose_name="Red social", max_length=200)
    url=models.URLField(verbose_name="Enlace", max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add= True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now= True, verbose_name= "Fecha de edición")
    
    class Meta:
        verbose_name = "enlace"
        verbose_name_plural = "enlaces"
        ordering = ['name']
    
    def __str__(self):
        return self.name 

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name= forms.CharField(label="Nombre", required=True, widget=forms.TextInput(
        attrs={'class':'form-control', 'placeholder': 'Escribe tu nombre'}
        ))
    email= forms.EmailField(label="Email", required=True, widget=forms.EmailInput(
        attrs={'class':'form-control', 'placeholder': 'Escribe tu e-mail'}
        ))
    content= forms.CharField(label="Contenido", required=True, widget=forms.Textarea(
        attrs={'class':'form-control', 'rows':3, 'placeholder':'Escribe tu mensaje'}
        ))

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category

# Create your views here.
def blog(request):
    posts =Post.objects.all()
    return render (request, "blog/blog.html", {'posts':posts})

def category(request, category_id):
    category= get_object_or_404 (Category, id= category_id)
    return render (request, "blog/category.html", {'category':category})

contact/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import ContactForm
from django.core.mail import EmailMessage

# Create your views here.
def contact(request):
    contact_form= ContactForm()
    
    if request.method=="POST":
        contact_form=ContactForm(data=request.POST)
        if contact_form.is_valid():
            name=request.POST.get('name', '')
            email=request.POST.get('email', '')
            content=request.POST.get('content', '')
            #enviamos el correo y redirecionamos
            email=EmailMessage(
                'La Caffetiera: Nuevo mensage de contacto',
                "De {{<}}>\n\nEscribió: \n\n{}".format(name, email, content),
                "no-contestar@inbox.mailtrap.io",
                ['rpindes@gmail.com'],
                reply_to=[email]
            )
            try:
                email.send()
            
            #Si todo ha ido bien, redireccionamos ok
            
                return redirect(reverse('contact')+ "?Ok")
            except:
            #Algo no ha ido bien, redireccionamos a Fail
            
                return redirect(reverse('contact')+ "?fail")
        
    return render(request, "contact/contact.html", {'form':contact_form})

core/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render (request,"core/home.html")

def about(request):
    return render (request,"core/about.html")


def store(request):
    return render(request, "core/store.html")

pages/views.py
from django.shortcuts import render, get_object_or_404
from .models import Page

# Create your views here.
def page(request, page_id):
    page=get_object_or_404(Page, id=page_id)
    return render(request, 'pages/sample.html', {'page':page})

services/views.py
from django.shortcuts import render
from .models import Service

# Create your views here.
def services(request):
    services= Service.objects.all()
    return render(request, "services/services.html", {'services':services})

social/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/blog.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}
  {% for post in posts %}
    <section class="page-section cta">
    <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-innerv text-center rounded">
          <h2 class="section-heading mb-5">
            <span class="section-heading-upper">{{post.published|date:"SHORT_DATE_FORMAT"}}</span>
            <span class="section-heading-lower">{{post.title}}</span>
          </h2>
          <p class="mb-0">
            <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{post.image.url}}" alt="">
          </p>
          <p class="mb-0 mbt"> {{post.content|linebreaks}}</p>
          <p class="mb-0 mbt">
            <span class="section-heading-under">Publicado por <em><b>{{post.author}}</b></em> en 
              <!--<em><a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em>-->
              {% for category in post.categories.all %}
                {{category.name}} 
                {% if not forloop.last %}, 
                {% endif %}
              {% endfor %}
            </span
          </p>
        </div>

      </div>
    </div>
    </div>
    </section>
  {% endfor %}
{% endblock %}


    

blog/templates/blog/category.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}
  {% for post in category.get_post.all %}
    <section class="page-section cta">
    <div class="conta-inner">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-innerv text-center rounded">
          <h2 class="section-heading mb-5">
            <span class="section-heading-upper">{{post.published|date:"SHORT_DATE_FORMAT"}}</span>
            <span class="section-heading-lower">{{post.title}}</span>
          </h2>
          <p class="mb-0">
            <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{post.image.url}}" alt="">
          </p>
          <p class="mb-0 mbt"> {{post.content|linebreaks}}</p>
          <p class="mb-0 mbt">
            <span class="section-heading-under">Publicado por <em><b>{{post.author}}</b></em> en 
              <!--<em><a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em>-->
              {% for category in post.categories.all %}
                {{category.name}} 
                {% if not forloop.last %}, 
                {% endif %}
              {% endfor %}
            </span
          </p>
        </div>

      </div>
    </div>
    </div>
    </section>
  {% endfor %}
{% endblock %}

contact/templates/contact/contact.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Contacto{% endblock %}

{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/contact.jpg' %}" alt="">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Envíanos tus dudas</span>
              <span class="section-heading-lower">Contacto</span>
            </h2>
            <!-- Formulario de contacto -->
            {% if 'ok' in request.GET %}
              <p><b>Su mensaje se ha enviado correctamente, en breve nos pondremos en contacto con usted. </b></p>
            {% endif %}
            <!--<form action="" method="POST">
              {% csrf_token %}
              <table>
                {{ form.as_table}}
                </table>
                <input type="submit" value="Enviar" />
              </form>-->

            <form action="" method="POST">
              {% csrf_token %}
                <div class="form-group">
                    <label>Nombre *</label>
                    <div class="input-group">
                      {{form.name}}
                    </div>
                    {{form.name.errors}}
                </div>
                <div class="form-group">
                    <label>Email *</label>
                    <div class="input-group">
                      {{form.email}}
                    </div>
                    <!--<ul class="errorlist">
                        <li>El email no es correcto.</li>
                    </ul>-->
                    {{form.email.errors}}
                </div>
                <div class="form-group">
                    <label>Mensaje *</label>
                    <div class="input-group">
                      {{form.content}}
                    </div>
                    {{form.content.errors}}
                </div>
                <div class="text-center">
                    <input type="submit" class="btn btn-primary btn-block py-2" value="Enviar">
                </div>
            </form> 
           
            <!-- Fin formulario de contacto -->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/about.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Historia{% endblock %}

{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/about.jpg' %}" alt="">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Tradición familiar italiana</span>
              <span class="section-heading-lower">Nuestra historia</span>
            </h2>
            <p>Fundada en 1987 consectetur adipiscing elit. Donec leo dui, vehicula vel dapibus ac, tempus non enim. Nunc tempor vel lacus vel gravida. Nam sit amet pellentesque mi. </p>
            <p>Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui.Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %} | Centro yoga italiano</title>

    {% load static %}
  

    <!-- Bootstrap -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Fuentes -->
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Estilos -->
    <link href="{% static 'core/css/business-casual.css' %}" rel="stylesheet">

  </head>

  <body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">Il miglior centro d'Italia</span>
      <span class="site-heading-lower">Centro yoga italiano</span>
    </h1>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'home' %}">La Caffettiera</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item  px-lg-4 {% if request.path == '/' %} active {% endif %}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'home'%}">Inicio</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path == '/about/' %} active {% endif %}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'about'%}">Historia</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path == '/services/' %} active {% endif %}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'services' %}">Servicios</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path == '/store/' %} active {% endif %}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'store'%}">Visítanos</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path == '/contact/' %} active {% endif %}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'contact'%}">Contacto</a>
            </li>
            <li class="nav-item px-lg-4 {% if request.path|slice:':6' == '/blog/' %} active {% endif %}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'blog:blog' %}">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <!-- Pié de página -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
            
              <a href="{{twitter}}" class="link">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            

          
            <a href="{{facebook}}" class="link">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          

          
            <a href="{{instagram}}" class="link">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          
	    </p>
        <!--<p class="m-0 mbt">
        	<a href="sample-html" class="link">Aviso legal</a> ·
        	<a href="sample-html" class="link">Cookies</a> ·
        	<a href="sample-html" class="link">Política de privacidad</a>-->
        {% load pages_extras %}
        {% get_page_list as page_list %}
        {% for page in page_list %}
          <a href="{% url 'page' page.id %}" class="link">{{page.title}}</a> {% if not forloop.last %}.{% endif %}
        {% endfor %}

		</p>
        <p class="m-0 mbt1">&copy; Centro yoga italiano 2025</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Inicio{% endblock %}

{% block content %}

<!-- Cabecera -->
<section class="page-section clearfix">
  <div class="container">
    <div class="intro">
      <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/img/intro.jpg' %}" alt="">
      <div class="intro-text left-0 text-center bg-faded p-5 rounded">
        <h2 class="section-heading mb-4">
          <span class="section-heading-upper">Déjate sorprender</span>
          <span class="section-heading-lower">Te gustará</span>
        </h2>
        <p class="mb-3">Trabajamos sólo con los mejores maestro de yoga. Una vez lo pruebes, notarás un cambio en tu vida que  será la mejor forma de empezar tu rutina diaria.
        </p>
        <div class="intro-button mx-auto">
          <a class="btn btn-primary btn-xl" href="store.html">Visítanos</a>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Mensaje -->
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner text-center rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Compromiso total</span>
            <span class="section-heading-lower">Garantizado</span>
          </h2>
          <p class="mb-0">Sed pulvinar blandit elit id venenatis. Ut eget lacus neque. Nullam justo quam, efficitur nec turpis vitae, efficitur posuere ligula. Proin ut turpis orci. Aenean porta sodales lectus faucibus pellentesque. In sed felis iaculis, rhoncus felis a, maximus mi.</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/services.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Servicios{% endblock %}

{% block content %}
<section class="page-section">
  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex mr-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-upper">La mezcla perfecta</span>
            <span class="section-heading-lower">Namasté</span>
          </h2>
        </div>
      </div>
      <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/img/products-01.jpg' %}" alt="">
      <div class="product-item-description d-flex ml-auto">
        <div class="bg-faded p-5 rounded">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In massa purus, posuere non neque sed, ultricies ornare magna. Donec eu lobortis ex. Morbi maximus tempor accumsan. Mauris pellentesque mauris id nibh vestibulum, id sodales lorem bibendum. Nunc at interdum velit. Donec nec sapien eget arcu imperdiet bibendum</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="page-section">
  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex mr-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-upper">El mejor acompañamiento</span>
            <span class="section-heading-lower">Producto original</span>
          </h2>
        </div>
      </div>
      <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/img/products-02.jpg' %}" alt="">
      <div class="product-item-description d-flex ml-auto">
        <div class="bg-faded p-5 rounded">
          <p class="mb-0">Morbi dapibus malesuada mollis. Nunc cursus velit eget cursus pharetra. Ut feugiat, dui id congue porttitor, sem erat pharetra dui, in ullamcorper quam nulla vitae quam. Sed blandit libero feugiat diam cursus, nec euismod ante consequat. Curabitur nec tincidunt ipsum, in tempor turpis. Sed ut metus a nisl rhoncus placerat.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="page-section">
  <div class="container">
    <div class="product-item">
      <div class="product-item-title d-flex">
        <div class="bg-faded p-5 d-flex mr-auto rounded">
          <h2 class="section-heading mb-0">
            <span class="section-heading-upper">Producto certificado</span>
            <span class="section-heading-lower">También vendemos</span>
          </h2>
        </div>
      </div>
      <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'core/img/products-03.jpg' %}" alt="">
      <div class="product-item-description d-flex ml-auto">
        <div class="bg-faded p-5 rounded">
          <p class="mb-0">Integer ac elementum lacus, consectetur cursus tellus. Suspendisse faucibus sapien massa, ac pharetra est aliquet a. In interdum feugiat ultrices. Aliquam eget tempor libero. Aliquam sit amet ante quis lectus fermentum bibendum. Ut molestie nulla in tellus euismod feugiat. Nunc varius erat nulla, eu dictum mi ultrices in.</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/store.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Visítanos{% endblock %}

{% block content %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner text-center rounded">
          <h2 class="section-heading mb-5">
            <span class="section-heading-upper">Te esperamos</span>
            <span class="section-heading-lower">Visítanos</span>
          </h2>
          <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
            <li class="list-unstyled-item list-hours-item d-flex">
              Lunes a viernes
              <span class="ml-auto">7:00 a 20:00</span>
            </li>
            <li class="list-unstyled-item list-hours-item d-flex">
              Sábados
              <span class="ml-auto">9:00 a 17:00</span>
            </li>
            <li class="list-unstyled-item list-hours-item d-flex">
              Domingos
              <span class="ml-auto">Cerrado</span>
            </li>
          </ul>
          <p class="address mb-5">
            <em>
              <strong>Avd. Infusiones nº 127</strong>
              <br>
              Barcelona
            </em>
          </p>
          <p class="mb-0">
            <small>
              <em>Llámanos y pregunta</em>
            </small>
            <br>
            (317) 585-8468
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

pages/templates/pages/sample.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Muestra{% endblock %}

{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <div class="about-heading-content mbtm">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5 forced">
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower">{{page.title}}</span>
            </h2>
            <div class="section-content">{{ page.content|safe }}
              {% if user.is_autothenticated %}
                <p><a herf="{% url 'admin:pages_page_change' page.id %}"> Editar </a></p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

services/templates/services/services.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Servicios{% endblock %}

{% block content %}
{% for service in services reversed%}
    <section class="page-section">
      <div class="container">
        <div class="product-item">
          <div class="product-item-title d-flex">
            <div class="bg-faded p-5 d-flex mr-auto rounded">
              <h2 class="section-heading mb-0">
                <span class="section-heading-upper">{{service.subtitle}}</span>
                <span class="section-heading-lower">{{service.title}}</span>
              </h2>
            </div>
          </div>
          <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{service.image.url}}" alt="">
          <div class="product-item-description d-flex ml-auto">
            <div class="bg-faded p-5 rounded">
              <p class="mb-0">{{service.content}}</p>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endfor %}
{% endblock %}